SandalineColony_Mart_Text_ClerkF_WelcomeToThePokemonMart::
	.string "Hi, welcome to the Pokémon Mart!\p"
	.string "Here you can buy useful Items to\n"
	.string "aid you in your journey as a\l"
	.string "Pokémon Trainer.\p"
	.string "Every Gym Badge you win will\n"
	.string "reward you with a broader\l"
	.string "selection of Items to choose\l"
	.string "from!$"

SandalineColony_Mart_Text_ClerkM_ThatGuyIsWaitingForSomeone::
	.string "Welcome to Sandaline Colony's\n"
	.string "Pokémon Mart!\p"
	.string "Are you looking for somebody?\n"
	.string "Could it be that guy between\l"
	.string "The shelves over there?\p"
	.string "I swear, I'm sure I've seen him\n"
	.string "somewhere, but I just can't\l"
	.string "remember where...$"

SandalineColony_Mart_Text_Bugsy_TookYouAWhile::
	.string "{COLOR GREEN}Bugsy: Took you long enough!\p"
	.string "This facility here is called\n"
	.string "a Pokémon Center.\p"
	.string "Every Pokémon Center serves two\n"
	.string "basic purposes. One of those is\l"
	.string "to sell useful Items that every\l"
	.string "Trainer needs to know!\p"
	.string "Follow me!$"

SandalineColony_Mart_Text_Bugsy_ThisIsAMart::
	.string "{COLOR GREEN}Bugsy: This section of a Pokémon\n"
	.string "Center is usually referred to as\l"
	.string "a Pokémon Mart\p"
	.string "Pokémon Marts used to be found\n"
	.string "in their own buildings, but they\l"
	.string "all merged with Pokémon Centers\l"
	.string "one year ago.$"

SandalineColony_Mart_Text_Bugsy_IdLikeToBuyPokeBalls::
	.string "{COLOR GREEN}Bugsy: Hi! I'd like to buy 10\n"
	.string "regular Poké Balls, please!$"

SandalineColony_Mart_Text_ClerkM_ThatWouldBeMoney::
	.string "{COLOR BLUE}Mart Clerk: That would be\n"
	.string "¥2,000.$"

SandalineColony_Mart_Text_Scene_BugsyPays::
	.string "Bugsy paid ¥2,000.$"

SandalineColony_Mart_Text_ClerkM_YouReceiveAPremierBall::
	.string "{COLOR BLUE}Mart Clerk: as per our policy,\n"
	.string "I'm throwing in a Premier Ball\l"
	.string "too.$"

SandalineColony_Mart_Text_Bugsy_ThankYou::
	.string "{COLOR GREEN}Bugsy: Thank you very much!\n$"

SandalineColony_Mart_Text_Bugsy_ItemsCostMoney::
	.string "{COLOR GREEN}Bugsy: As you can imagine, Items\n"
	.string "are traded for money. If you're\l"
	.string "broke, a Pokémon Mart won't do\l"
	.string "any good for you.\p"
	.string "But it's still worth coming to a\n"
	.string "Pokémon Center, and I'll show\l"
	.string "you why. Let's go!$"
