RouteOasis_Text_Bugsy_YouWantToBecomeATrainer::
	.string "{COLOR GREEN}Bugsy: So, {PLAYER}...\p"
	.string "Since you want to take on the\n"
	.string "Gyms' Challenge, it's time\l"
	.string "you're given your first\l"
	.string "companion.\p"
	.string "Which is why I asked you\n"
	.string "to come here!$"

RouteOasis_Text_Bugsy_JoeyNewGymLeader::
	.string "{COLOR GREEN}Bugsy: And since you're going to\n"
	.string "become Azalea Town's new\l"
	.string "Gym Leader, Joey, I have\l"
	.string "a present for you too.$"

RouteOasis_Text_Joey_BugsyDidNotNeedTo::
	.string "{COLOR BLUE}Joey: Dear Bugsy, you didn't\n"
	.string "have to!\p"
	.string "As you know, I've been a Pokémon\n"
	.string "Trainer since my childhood,\l"
	.string "just like you!\p"
	.string "I even won the Hive Badge\n"
	.string "from you!$"

RouteOasis_Text_Bugsy_TheseMonsAreRare::
	.string "{COLOR GREEN}Bugsy: A bit shy, aren't we?\p"
	.string "These Pokémon are rare.\n"
	.string "You have to look very hard\l"
	.string "to find one in the wild!\p"
	.string "Come on, bud! Let's\n"
	.string "just celebrate your new job as a\l"
	.string "Gym Leader!$"

RouteOasis_Text_Bugsy_LastChallenger::
	.string "{COLOR GREEN}Bugsy: And by the way, {PLAYER},\n"
	.string "I want you to be my last\l"
	.string "challenger, agreed?\p"
	.string "Anyway, enough chitty-chatting.\n"
	.string "Excuse me, {PLAYER}.$"

RouteOasis_Text_Bugsy_PlayerPickMon::
	.string "{COLOR GREEN}Bugsy: There!\n"
	.string "You go first, {PLAYER}.\p"
	.string "These Poké Balls carry three\n"
	.string "rare Pokémon.\l"
	.string "And there's three of us!\l"
	.string "Do you know what that means?\p"
	.string "It means we'll take one each!\p"
	.string "And since it will be your first\n"
	.string "own Pokémon, {PLAYER},\l"
	.string "you get to choose first.$"

RouteOasis_Text_Bugsy_JoeyWillPickSecond::
	.string "{COLOR GREEN}Bugsy: Next, Joey will pick one\n"
	.string "of the remaining Pokémon.$"

RouteOasis_Text_Bugsy_IWillPickLast::
	.string "{COLOR GREEN}Bugsy: And whichever is left,\n"
	.string "I'll take it with me!$"

RouteOasis_Text_Bugsy_GoAheadPickOne::
	.string "{COLOR GREEN}Bugsy: Go ahead, {PLAYER},\n"
	.string "check out the Poké Balls.\l"
	.string "Take your time.$"

RouteOasis_Text_Bugsy_DoNotGoAway::
	.string "{COLOR GREEN}Bugsy: Slow down, {PLAYER}!\n"
	.string "Are you walking away without my\l"
	.string "present?\p"
	.string "Check out the Poké Balls.\n"
	.string "Take your time.$"

RouteOasis_Text_Joey_DoNotGoAway::
	.string "{COLOR BLUE}Joey: Hey, {PLAYER}, are you\n"
	.string "going away without Bugsy's\l"
	.string "present?\p"
	.string "Check out those Poké Balls.\n"
	.string "Don't keep us waiting too long!$"

RouteOasis_Text_Bugsy_CheckOutPokeballs::
	.string "{COLOR GREEN}Bugsy: Check out the Poké Balls.\n"
	.string "Take your time.$"

RouteOasis_Text_Joey_CheckOutPokeballs::
	.string "{COLOR BLUE}Joey: Check out those\n"
	.string "Poké Balls. Don't keep us\l"
	.string "waiting too long!$"

RouteOasis_Text_Ball_WantToPickThisOne::
	.string "{STR_VAR_3}This is the {STR_VAR_2}-type Pokémon\n"
	.string "{STR_VAR_1}.\pIs this the one you want"
	.string "\nto keep?$"

RouteOasis_Text_Ball_StarterHasBecomeCompanion::
	.string "{STR_VAR_3}{STR_VAR_1} has become\n"
	.string "your first companion\l"
	.string "in this adventure!$"

RouteOasis_Text_Bugsy_YourTurnJoey::
	.string "{COLOR GREEN}Bugsy: It's your turn, Joey!\p"
	.string "{PLAYER} has chosen {STR_VAR_1}.\n"
	.string "Now there are two Pokémon left.\l"
	.string "You may take whichever one you\l"
	.string "like!$"

RouteOasis_Text_Joey_Dots::
	.string "{COLOR BLUE}Joey: .{PAUSE 60} .{PAUSE 60} .{PAUSE 60}\n$"

RouteOasis_Text_Joey_WhichOneShouldIPick::
	.string "{COLOR BLUE}Joey: So, which one should I\n"
	.string "pick?$"

RouteOasis_Text_Joey_AdvantageOverPlayerOrOverBugsy::
	.string "{COLOR BLUE}Joey: If I pick {STR_VAR_2}, I'll\n"
	.string "have an advantage over\l"
	.string "{PLAYER}'s {STR_VAR_1}...\p"
	.string "But if I go with {STR_VAR_3},\n"
	.string "I can knock out Bugsy's\l"
	.string "{STR_VAR_2} with ease...$"

RouteOasis_Text_Joey_IllTakeThisOne::
	.string "{COLOR BLUE}Joey: Do I even need to ask?\n"
	.string "{STR_VAR_3}, I choose you!$"

RouteOasis_Text_Ball2_JoeyPicked::
	.string "Joey decided to take {STR_VAR_3}\n"
	.string "with him!$"

RouteOasis_Text_Bugsy_ThatLeavesOneForMe::
	.string "{COLOR GREEN}Bugsy: That leaves {STR_VAR_2}\n"
	.string "for me to take!$"

RouteOasis_Text_Ball3_BugsyPicked::
	.string "Bugsy is keeping {STR_VAR_2}.$"
