RouteOasis_Text_Bugsy_YouWantToBecomeATrainer::
	.string "{COLOR GREEN}Bugsy: So, {PLAYER}…\p"
	.string "Since you want to take on the\n"
	.string "Gyms' Challenge, it's time\l"
	.string "you're given your first\l"
	.string "companion.\p"
	.string "Which is why I asked you\n"
	.string "to come here!$"

RouteOasis_Text_Bugsy_JoeyNewGymLeader::
	.string "{COLOR GREEN}Bugsy: And since you're going to\n"
	.string "become Azalea Town's new\l"
	.string "Gym Leader, Joey, I have\l"
	.string "a present for you too.$"

RouteOasis_Text_Joey_BugsyDidNotNeedTo::
	.string "{COLOR BLUE}Joey: Dear Bugsy, you didn't\n"
	.string "have to!\p"
	.string "As you know, I've been a Pokémon\n"
	.string "Trainer since my childhood,\l"
	.string "just like you!\p"
	.string "I even won the Hive Badge\n"
	.string "from you!$"

RouteOasis_Text_Bugsy_TheseMonsAreRare::
	.string "{COLOR GREEN}Bugsy: A bit shy, aren't we?\p"
	.string "These Pokémon are rare.\n"
	.string "You have to look very hard\l"
	.string "to find one in the wild!\p"
	.string "Come on, bud! Let's\n"
	.string "just celebrate your new job as a\l"
	.string "Gym Leader!$"

RouteOasis_Text_Bugsy_LastChallenger::
	.string "{COLOR GREEN}Bugsy: And by the way, {PLAYER},\n"
	.string "I want you to be my last\l"
	.string "challenger, agreed?\p"
	.string "Anyway, enough chitty-chatting.\n"
	.string "Excuse me, {PLAYER}.$"

RouteOasis_Text_Bugsy_PlayerPickMon::
	.string "{COLOR GREEN}Bugsy: There!\n"
	.string "You go first, {PLAYER}.\p"
	.string "These Poké Balls carry three\n"
	.string "rare Pokémon.\l"
	.string "And there's three of us!\l"
	.string "Do you know what that means?\p"
	.string "It means we'll take one each!\p"
	.string "And since it will be your first\n"
	.string "own Pokémon, {PLAYER},\l"
	.string "you get to choose first.$"

RouteOasis_Text_Bugsy_JoeyWillPickSecond::
	.string "{COLOR GREEN}Bugsy: Next, Joey will pick one\n"
	.string "of the remaining Pokémon.$"

RouteOasis_Text_Bugsy_IWillPickLast::
	.string "{COLOR GREEN}Bugsy: And whichever is left,\n"
	.string "I'll take it with me!$"

RouteOasis_Text_Bugsy_GoAheadPickOne::
	.string "{COLOR GREEN}Bugsy: Go ahead, {PLAYER},\n"
	.string "check out the Poké Balls.\l"
	.string "Take your time.$"

RouteOasis_Text_Tutorial_WalkAndRun::
	.string "Use {DPAD_ANY} to walk.\n"
	.string "Hold down {B_BUTTON} to run.$"

RouteOasis_Text_Bugsy_DoNotGoAway::
	.string "{COLOR GREEN}Bugsy: Slow down, {PLAYER}!\n"
	.string "Are you walking away without my\l"
	.string "present?\p"
	.string "Check out the Poké Balls.\n"
	.string "Take your time.$"

RouteOasis_Text_Joey_DoNotGoAway::
	.string "{COLOR BLUE}Joey: Hey, {PLAYER}, are you\n"
	.string "going away without Bugsy's\l"
	.string "present?\p"
	.string "Check out those Poké Balls.\n"
	.string "Don't keep us waiting too long!$"

RouteOasis_Text_Bugsy_CheckOutPokeballs::
	.string "{COLOR GREEN}Bugsy: Check out the Poké Balls.\n"
	.string "Take your time.$"

RouteOasis_Text_Joey_CheckOutPokeballs::
	.string "{COLOR BLUE}Joey: Check out those\n"
	.string "Poké Balls. Don't keep us\l"
	.string "waiting too long!$"

RouteOasis_Text_Ball_WantToPickThisOne::
	.string "{STR_VAR_3}This is the {STR_VAR_2}-type Pokémon\n"
	.string "{STR_VAR_1}.\pIs this the one you want"
	.string "\nto keep?$"

RouteOasis_Text_Ball_StarterHasBecomeCompanion::
	.string "{STR_VAR_3}{STR_VAR_1} has become\n"
	.string "your first companion\l"
	.string "in this adventure!$"

RouteOasis_Text_Bugsy_YourTurnJoey::
	.string "{COLOR GREEN}Bugsy: It's your turn, Joey!\p"
	.string "{PLAYER} has chosen {STR_VAR_1}.\n"
	.string "Now there are two Pokémon left.\l"
	.string "You may take whichever one you\l"
	.string "like!$"

RouteOasis_Text_Joey_Dots::
	.string "{COLOR BLUE}Joey: .{PAUSE 60} .{PAUSE 60} .{PAUSE 60}\n$"

RouteOasis_Text_Joey_WhichOneShouldIPick::
	.string "{COLOR BLUE}Joey: So, which one should I\n"
	.string "pick?$"

RouteOasis_Text_Joey_AdvantageOverPlayerOrOverBugsy::
	.string "{COLOR BLUE}Joey: If I pick {STR_VAR_2}, I'll\n"
	.string "have an advantage over\l"
	.string "{PLAYER}'s {STR_VAR_1}…\p"
	.string "But if I go with {STR_VAR_3},\n"
	.string "I can knock out Bugsy's\l"
	.string "{STR_VAR_2} with ease…$"

RouteOasis_Text_Joey_IllTakeThisOne::
	.string "{COLOR BLUE}Joey: Do I even need to ask?\n"
	.string "{STR_VAR_3}, I choose you!$"

RouteOasis_Text_Ball2_JoeyPicked::
	.string "Joey decided to take {STR_VAR_3}\n"
	.string "with him!$"

RouteOasis_Text_Bugsy_ThatLeavesOneForMe::
	.string "{COLOR GREEN}Bugsy: That leaves {STR_VAR_2}\n"
	.string "for me to take!$"

RouteOasis_Text_Ball3_BugsyPicked::
	.string "Bugsy is keeping {STR_VAR_2}.$"

RouteOasis_Text_Bugsy_OneThingLeftToDo::
	.string "{COLOR GREEN}Bugsy: There's only one thing\n"
	.string "left to do now.\l"
	.string "Joey, can I count on you?$"

RouteOasis_Text_Joey_AnswerBugsySure::
	.string "{COLOR BLUE}Joey: Sure thing!$"

RouteOasis_Text_Joey_WeNeedToShowPlayerHowToBattle::
	.string "{COLOR BLUE}Joey: We need to show {PLAYER} how\n"
	.string "to have a Pokémon Battle!\p"
	.string "And the best way to do that is,\n"
	.string "well, to battle!\l"
	.string "This way, you and {STR_VAR_1} will\l"
	.string "get to know each other a little!$"

RouteOasis_Text_Bugsy_FairBattlesAreGood::
	.string "{COLOR GREEN}Bugsy: That's right!\p"
	.string "{PLAYER}, I know you're a nice\n"
	.string "person, and Joey is a good guy.\l"
	.string "You don't need to worry about\l"
	.string "hurting {STR_VAR_1}. Fair battles\l"
	.string "are the best recipe for a tight\l"
	.string "bond with your Pokémon!$"

RouteOasis_Text_Joey_IllGoEasyOnYou::
	.string "{COLOR BLUE}Joey: Then it's settled!\p"
	.string "Don't worry, {PLAYER}, I'll go\n"
	.string "easy on you and {STR_VAR_1}.\p"
	.string "Let's go!$"

RouteOasis_Text_Joey_TextWhenHeLoses::
	.string "Not bad! Not bad at all!$"

RouteOasis_Text_Joey_TextWhenHeWins::
	.string "That means, I win!$"

RouteOasis_Text_Joey_AfterHeLoses::
	.string "{COLOR BLUE}Joey: Hey, you aced it!\p"
	.string "Did you notice that your Pokémon\n"
	.string "has become stronger?\l"
	.string "That's right, defeating other\l"
	.string "Pokémon is the key to… well,\l"
	.string "defeat even more Pokémon!\p"
	.string "To win battles more easily, you\n"
	.string "have to win battles that you can\l"
	.string "already win. Sounds complicated?\p"
	.string "Don't wrap your head about it,\n"
	.string "you'll understand everything as\l"
	.string "you keep battling.$"

RouteOasis_Text_Bugsy_AfterJoeyLoses::
	.string "{COLOR GREEN}Bugsy: That's right!\p"
	.string "And the stronger the Pokémon you\n"
	.string "defeat, the faster your Pokémon\l"
	.string "matures.$"

RouteOasis_Text_Joey_AfterHeWins::
	.string "{COLOR BLUE}Joey: Too bad!\p"
	.string "But don't feel ashamed. It was\n"
	.string "your first battle after all.\p"
	.string "Anyway, once you start winning,\n"
	.string "winning more fights becomes\l"
	.string "progressively easier.\l"
	.string "A Pokémon grows stronger by\l"
	.string "defeating other Pokémon.\p"
	.string "It may sound a bit complicated,\n"
	.string "but I promise it'll become clear\l"
	.string "very soon.$"

RouteOasis_Text_Bugsy_AfterJoeyWins::
	.string "{COLOR GREEN}Bugsy: That's right!\p"
	.string "Stronger opponents will make\n"
	.string "your Pokémon mature faster, if\l"
	.string "you manage to take them down.\p"
	.string "If you find yourself losing a\n"
	.string "lot, you just have to train!$"

RouteOasis_Text_Bugsy_IHaveRemedies::
	.string "{COLOR GREEN}Bugsy: Hold on, {PLAYER}. I have\n"
	.string "a bunch of remedies in my bag.\l"
	.string "Let me use a few to fully heal\l"
	.string "your Pokémon.$"

RouteOasis_Text_HealExplanation::
	.string "Your party has been fully\n"
	.string "healed!\p"
	.string "When your party is healed,\n"
	.string "all your Pokémon get all their\l"
	.string "Health Points back, and every\l"
	.string "Status Condition is removed.\l"
	.string "Power Points are also refilled.$"

RouteOasis_Text_Bugsy_MyTurn::
	.string "{COLOR GREEN}Bugsy: Okay, my turn!$"

RouteOasis_Text_Bugsy_TextWhenHeLoses::
	.string "Nice! I bet winning my Badge is\n"
	.string "going to be a walk in the park!$"

RouteOasis_Text_Bugsy_TextWhenHeWins::
	.string "It's okay, {PLAYER}. You just\n"
	.string "need to train a little.$"

RouteOasis_Text_Bugsy_AfterHeLoses::
	.string "{COLOR GREEN}Bugsy: Well done!\n"
	.string "Your Pokémon has grown a little\l"
	.string "stronger!\p"
	.string "But remember, the weaker your\n"
	.string "opponents are, the slower your\l"
	.string "Pokémon grow.$"

RouteOasis_Text_Bugsy_AfterHeWins::
	.string "{COLOR GREEN}Bugsy: Aw, too bad!\n"
	.string "I was hoping for you to win this\l"
	.string "one!\p"
	.string "Well, anyway, remember what we\n"
	.string "said earlier about Pokémon\l"
	.string "growing stronger by fighting?\p"
	.string "Note this: the weaker your\n"
	.string "opponents are, the slower your\l"
	.string "Pokémon grow.$"

RouteOasis_Text_Bugsy_LetMeHealAgain::
	.string "{COLOR GREEN}Bugsy: Now, let me heal your\n"
	.string "Pokémon again!$"

RouteOasis_Text_Bugsy_HealJoeysPokemon::
	.string "{COLOR GREEN}Bugsy: Joey, let me quickly heal\n"
	.string "yours too!$"

RouteOasis_Text_Joey_ThanksBugsy::
	.string "{COLOR BLUE}Joey: Thank you, Bugsy!$"

RouteOasis_Text_Bugsy_YourFirstTask::
	.string "{COLOR GREEN}Bugsy: Now, {PLAYER}, since\n"
	.string "we're done here, I'm giving you\l"
	.string "a little task.\p"
	.string "Are you ready to hear it?$"

RouteOasis_Text_Bugsy_GoToThePokemonCenter::
	.string "{COLOR GREEN}Bugsy: You have to visit the\n"
	.string "Pokémon Center at the Colony!\p"
	.string "If you've never heard of a\n"
	.string "Pokémon Center, feel free to ask\l"
	.string "whoever you wish. HOWEVER!\p"
	.string "Asking people to walk you to the\n"
	.string "goal is out of the question! You\l"
	.string "must find it on your own!\p"
	.string "Find me there!$"

RouteOasis_Text_Bugsy_ImGoing::
	.string "{COLOR GREEN}Bugsy: I'm going, see ya!$"

RouteOasis_Text_Joey_ImGoingToo::
	.string "{COLOR BLUE}Joey: Don't ask why he had to\n"
	.string "make it so awkward.\p"
	.string "Anyway, finding a Pokémon Center\n"
	.string "in Sandaline Colony isn't hard\l"
	.string "at all. You actually have to try\l"
	.string "not to see it!$"
