Route33_Text_Joey_BugsyIsWaiting::
	.string "{COLOR BLUE}Joey: Bugsy is waiting for you\n"
	.string "inside the Pokémon Center.\l"
	.string "You're way off track here!$"

Route33_Text_Joey_BlockRoadBugsyIsWaiting::
	.string "{COLOR BLUE}Joey: {PLAYER}, are you looking\n"
	.string "for Bugsy?\p"
	.string "He's waiting for you inside the\n"
	.string "Pokémon Center.\l"
	.string "You're way off track here!$"

Route33_Text_Joey_BringYourPokedexHere::
	.string "{COLOR BLUE}Joey: Hey, didn't you receive\n"
	.string "a Pokédex when you arrived here?\p"
	.string "You told me that you're staying\n"
	.string "at Radiosa Hostel. Have you left\l"
	.string "your brand new Pokédex there?\p"
	.string "I want to show you something\n"
	.string "important, but it'd be pretty\l"
	.string "cool if you had it with you!$"

Route33_Text_Joey_YouWantToGoToBugsysGym::
	.string "{COLOR BLUE}Joey: {PLAYER}!\n"
	.string "You're heading to Azalea Town to\l"
	.string "battle Bugsy in his Gym, right?\p"
	.string "It's going to be hard with\n"
	.string "{STR_VAR_1} alone, I'll tell ya!\p"
	.string "You'll be better off knowing how\n"
	.string "to catch more Pokémon.$"

Route33_Text_TrainerTipsLedges::
	.string "TRAINER TIPS!\n"
	.string "Jump from a one-way ledge to\l"
	.string "reach hidden areas or take\l"
	.string "little shortcuts. But don't be\l"
	.string "too hasty! Once you've jumped\l"
	.string "off it, there's no jumping back!$"

Route33_Text_Joey_ThereIsAGeodude::
	.string "{COLOR BLUE}Joey: Look! That's a Geodude\n"
	.string "over there! It's rare to see one\l"
	.string "on this Route!$"

Route33_Text_Joey_JustWatch::
	.string "{COLOR BLUE}Joey: Just watch!$"

Route33_Text_Joey_Yell::
	.string "{COLOR BLUE}Joey: HEEEEEEEEERE!!!!!$"

Route33_Text_Joey_ThisIsHowYouCatch::
	.string "{COLOR BLUE}Joey: See? This is how you catch\n"
	.string "wild Pokémon. Throw a Poké Ball\l"
	.string "at them and hope it stays shut!\p"
	.string "But let me tell ya, it's a lot\n"
	.string "easier to catch Pokémon that\l"
	.string "have been weakened, than to\l"
	.string "catch Pokémon in mint condition.$"

Route33_Text_CatchEasierExplanation::
	.string "Wild Pokémon with few HPs left\n"
	.string "are easier to catch. Poké Balls\l"
	.string "thrown at them have a higher\l"
	.string "chance of success.\p"
	.string "To maximize your odds, try to\n"
	.string "deal damage until the Pokémon\l"
	.string "you want to catch is left with\l"
	.string "just 1 HP.\p"
	.string "Inflicting a Status Condition on\n"
	.string "a wild Pokémon will raise your\l"
	.string "chances even more.\p"
	.string "Be careful not to knock it out,\n"
	.string "because fainting a wild Pokémon\l"
	.string "will end the battle instantly.$"
