Route33_Text_Joey_BugsyIsWaiting::
	.string "{COLOR BLUE}Joey: Bugsy is waiting for you\n"
	.string "inside the Pokémon Center.\l"
	.string "You're way off track here!$"

Route33_Text_Joey_BlockRoadBugsyIsWaiting::
	.string "{COLOR BLUE}Joey: {PLAYER}, are you looking\n"
	.string "for Bugsy?\p"
	.string "He's waiting for you inside the\n"
	.string "Pokémon Center.\l"
	.string "You're way off track here!$"

Route33_Text_Joey_BringYourPokedexHere::
	.string "{COLOR BLUE}Joey: Hey, didn't you receive\n"
	.string "a Pokédex when you arrived here?\p"
	.string "You told me that you're staying\n"
	.string "at Radiosa Hostel. Have you left\l"
	.string "your brand new Pokédex there?\p"
	.string "I want to show you something\n"
	.string "important, but it'd be pretty\l"
	.string "cool if you had it with you!$"
