SandalineColony_PokemonCenter_Text_Bugsy_ThisIsAPokemonCenter::
	.string "{COLOR GREEN}Bugsy: This is the main hall\n"
	.string "of a Pokémon Center, where\l"
	.string "you'll spend most of your time\l"
	.string "when paying a visit.\p"
	.string "Let's head to the counter!$"

SandalineColony_PokemonCenter_Text_Bugsy_TheMainAttraction::
	.string "{COLOR GREEN}Bugsy: A Pokémon Center's main\n"
	.string "attraction is none other than\l"
	.string "the nurse herself!\p"
	.string "When your Pokémon are hurt,\n"
	.string "your best option is to storm\l"
	.string "into a Pokémon Center and ask\l"
	.string "the nurse to heal them.\p"
	.string "Why don't you give it a shot?\n"
	.string "Your Pokémon doesn't need to\l"
	.string "be healed right now, but hey,\l"
	.string "the service is absolutely free\l"
	.string "anyway!$"

SandalineColony_PokemonCenter_Text_Nurse_HowMayIHelpYou::
	.string "Hello dear, how may I help you?$"

SandalineColony_PokemonCenter_Text_Nurse_DoYouWantToHeal::
	.string "Welcome to Sandline Colony's\n"
	.string "Pokémon Center!\p"
	.string "Is this your first time in a\n"
	.string "Pokémon Center?\p"
	.string "My job is to take care of your\n"
	.string "Pokémon Party and heal your\l"
	.string "companions to perfect health.\p"
	.string "Would you like me to heal your\n"
	.string "Pokémon?$"

SandalineColony_PokemonCenter_Text_Nurse_WheneverYouWantToHeal::
	.string "Whenever you want me to handle\n"
	.string "your tired Pokémon,\l"
	.string "just let me know!$"

SandalineColony_PokemonCenter_Text_Nurse_MayIHaveYourPokemon::
	.string "Sure, may I have your Pokémon\n"
	.string "for a few moments?$"

SandalineColony_PokemonCenter_Text_Scene_PlayerHandsTheParty::
	.string "{COLOR DARK_GRAY}{PLAYER} handed {STR_VAR_1}\n"
	.string "to the nurse.$"

SandalineColony_PokemonCenter_Text_Nurse_IllPutThemInThisMachine::
	.string "Okay, this is how it's done:\n"
	.string "I lay the Poké Ball on this\l"
	.string "machine and I start it.$"

SandalineColony_PokemonCenter_Text_Nurse_Done::
	.string "Aaand{PAUSE 30}.{PAUSE 30}.{PAUSE 30}.{PAUSE 60}Done!$"

SandalineColony_PokemonCenter_Text_Nurse_ThankYourForYourPatience::
	.string "Thank you for your patience.\n"
	.string "Your Pokémon is well rested.\l"
	.string "I'll hand it back to you now.$"

SandalineColony_PokemonCenter_Text_Scene_PlayerReceivedMonBack::
	.string "{COLOR DARK_GRAY}{PLAYER} received {STR_VAR_1} back.$"
