SandalineColony_PokemonCenter_Text_Nurse_ThisIsAPokemonCenter::
	.string "This is Sandaline Colony's\n"
	.string "Pokémon Center.\p"
	.string "Pokémon Centers are facilities\n"
	.string "which offer various services to\l"
	.string "every Pokémon Trainer.\p"
	.string "I'm here to take care of tired\n"
	.string "Pokémon and heal them to full\l"
	.string "health.\p"
	.string "On your right you can find a PC\n"
	.string "running the AltariOS operating\l"
	.string "system, which allows you to\l"
	.string "store all your Pokémon on the\l"
	.string "Johto Cloud.\p"
	.string "Finally, the door on your left\n"
	.string "leads to the Pokémon Mart, where\l"
	.string "you can buy Items that can help\l"
	.string "you on your journey.$"

SandalineColony_PokemonCenter_Text_Nurse_YouAreLookingForAFriend::
	.string "You are looking for a friend?\p"
	.string "If you don't see them in the\n"
	.string "hall, you might want to look\l"
	.string "inside the Pokémon Mart. Simply\l"
	.string "take the door on your left.$"

SandalineColony_PokemonCenter_Text_Nurse_TellMeIfYouNeed::
	.string "Let me know if you need\n"
	.string "anything!$"

SandalineColony_PokemonCenter_Text_Nurse_IsThereAnythingElse::
	.string "Is there anything else I can do\n"
	.string "for you?$"

SandalineColony_PokemonCenter_Text_Bugsy_ThisIsAPokemonCenter::
	.string "{COLOR GREEN}Bugsy: This is the main hall\n"
	.string "of a Pokémon Center, where\l"
	.string "you'll spend most of your time\l"
	.string "when paying a visit.\p"
	.string "Let's head to the counter!$"

SandalineColony_PokemonCenter_Text_Bugsy_TheMainAttraction::
	.string "{COLOR GREEN}Bugsy: A Pokémon Center's main\n"
	.string "attraction is none other than\l"
	.string "the nurse herself!\p"
	.string "When your Pokémon are hurt,\n"
	.string "your best option is to storm\l"
	.string "into a Pokémon Center and ask\l"
	.string "the nurse to heal them.\p"
	.string "Why don't you give it a shot?\n"
	.string "Your Pokémon doesn't need to\l"
	.string "be healed right now, but hey,\l"
	.string "the service is absolutely free\l"
	.string "anyway!$"

SandalineColony_PokemonCenter_Text_Nurse_HowMayIHelpYou::
	.string "Hello dear, how may I help you?$"

SandalineColony_PokemonCenter_Text_Nurse_DoYouWantToHeal::
	.string "Welcome to Sandline Colony's\n"
	.string "Pokémon Center!\p"
	.string "Is this your first time in a\n"
	.string "Pokémon Center?\p"
	.string "My job is to take care of your\n"
	.string "Pokémon Party and heal your\l"
	.string "companions to perfect health.\p"
	.string "Would you like me to heal your\n"
	.string "Pokémon?$"

SandalineColony_PokemonCenter_Text_Nurse_WheneverYouWantToHeal::
	.string "Whenever you want me to handle\n"
	.string "your tired Pokémon,\l"
	.string "just let me know!$"

SandalineColony_PokemonCenter_Text_Nurse_MayIHaveYourPokemon::
	.string "Sure, may I have your Pokémon\n"
	.string "for a few moments?$"

SandalineColony_PokemonCenter_Text_Scene_PlayerHandsTheParty::
	.string "{COLOR DARK_GRAY}{PLAYER} handed {STR_VAR_1}\n"
	.string "to the nurse.$"

SandalineColony_PokemonCenter_Text_Nurse_IllPutThemInThisMachine::
	.string "Okay, this is how it's done:\n"
	.string "I lay the Poké Ball on this\l"
	.string "machine and I start it.$"

SandalineColony_PokemonCenter_Text_Nurse_Done::
	.string "Aaand{PAUSE 30}.{PAUSE 30}.{PAUSE 30}.{PAUSE 60} Done!$"

SandalineColony_PokemonCenter_Text_Nurse_ThankYourForYourPatience::
	.string "Thank you for your patience.\n"
	.string "Your Pokémon is well rested.\l"
	.string "I'll hand it back to you now.$"

SandalineColony_PokemonCenter_Text_Scene_PlayerReceivedMonBack::
	.string "{COLOR DARK_GRAY}{PLAYER} received {STR_VAR_1} back.$"

SandalineColony_PokemonCenter_Text_Bugsy_AskTheNurseToHealYourPokemon::
	.string "{COLOR GREEN}Bugsy: Come on, ask the nurse to\n"
	.string "heal your Pokémon!$"

SandalineColony_PokemonCenter_Text_Bugsy_WhereAreYouGoing::
	.string "{COLOR GREEN}Bugsy: Where are you going?$"

SandalineColony_PokemonCenter_Text_Bugsy_PokemonCenterAreImportant::
	.string "{COLOR GREEN}Bugsy: Isn't it convenient?\p"
	.string "HPs are fully restored,\n"
	.string "PPs are fully restored too,\l"
	.string "Status Conditions go away,\l"
	.string "all of this without the need\l"
	.string "to spend a single coin.\p"
	.string "A Pokémon Center is a Trainer's\n"
	.string "beacon. It's an icon of safety,\l"
	.string "the right place to look for when\l"
	.string "things get hard.$"

SandalineColony_PokemonCenter_Text_Bugsy_HeadToAzaleaTown::
	.string "{COLOR GREEN}Bugsy: {PLAYER}, I have nothing\n"
	.string "else to say, for now.\p"
	.string "You should make your way to\n"
	.string "Azalea Town, where my Gym, soon\l"
	.string "to be Joey's, is located.\p"
	.string "While you head there, Joey is\n"
	.string "going to show you something\l"
	.string "essential.\p"
	.string "Until then!$"
